"""Hand-authored labeled dataset for the return-reason classifier.

Two classes:
  - "hardware_defect": something is physically broken/faulty on the item.
  - "personal_dissatisfaction": the item works, the customer just doesn't want it.

Phrasing deliberately spans the full SeasonMart catalog vocabulary (cooling,
heating, weather gear, clothing, accessories, personal care, home) so the
TF-IDF + logistic regression classifier generalizes to any product type the
storefront might send back, not just the three demo appliances it started with.

Both lists are kept roughly balanced in size so neither class dominates the
decision boundary at training time.
"""

HARDWARE_DEFECT = [
    # Appliances — cooling
    "The cooler stopped working after just two days, the motor makes a grinding noise.",
    "Cooler motor seized up completely after a week of normal use.",
    "The cooler's water pump is leaking from the bottom, clearly a manufacturing defect.",
    "Ice formed inside the cooler's cooling pads and it cracked the plastic body.",
    "The cooler tank has a crack and water leaks all over the floor.",
    "Cooling pads arrived torn and the pump doesn't draw water at all.",
    "Water is leaking from a crack in the cooler's side panel, defective housing.",
    "The AC unit stopped cooling after one week, I think the compressor is dead.",
    "Split AC is leaking refrigerant from the indoor unit, there's an oily residue.",
    "Window AC trips the breaker every time I turn it on, electrical fault.",
    "The AC remote came dead on arrival and the unit itself has no manual override.",
    # Fans
    "Fan blades are wobbling and it makes a loud rattling sound every time I switch it on.",
    "Fan motor overheats and shuts off automatically within minutes of use.",
    "The remote control doesn't pair with the fan, the receiver seems faulty.",
    "Several of the blades on this fan are chipped right out of the box.",
    "Switch button is jammed, physically cannot turn the fan off.",
    "The oscillation mechanism is broken, fan only points in one direction now.",
    "The fan's capacitor burned out and now it won't start spinning.",
    "Ceiling fan rotor is misaligned, there's a visible wobble at every speed.",
    "The neck fan battery won't hold a charge, dies in under ten minutes now.",
    "USB desk fan motor is making a grinding sound and the speed is stuck on low.",
    "Pedestal fan base cracked while assembling it, parts clearly defective.",
    # Heaters
    "Heater won't turn on at all, I think the heating element is broken.",
    "There's a burning smell coming from the heater, seems like a wiring issue.",
    "Display panel on the heater is completely dead, no power indicator lights up.",
    "Thermostat on the heater is stuck and it keeps overheating the room dangerously.",
    "Heater trips the circuit breaker every single time I plug it in.",
    "The heater's fan inside rattles loudly, something is loose or broken internally.",
    "The grille on the heater is cracked and a fan blade inside is bent.",
    "Oil-filled radiator is leaking oil from a seam, this is a defect.",
    "Infrared heater lamp cracked after the first use and no longer glows.",
    "Panel heater has a dead zone, half the surface stays cold while the other burns.",
    "Convection heater's thermostat clicks on and off nonstop, something is wrong.",
    # Water heaters / electrical
    "Storage water heater is leaking from the bottom, water pooling under it.",
    "Instant water heater throws sparks when switched on, this is dangerous.",
    "Electric blanket's wire has snapped inside, there's a dead cold spot.",
    "Heating pad gets smoking hot on one side, I'm sure the wiring is faulty.",
    "Immersion water rod short-circuited the first time I plugged it in.",
    "Towel warmer rail is only heating on one side, the other half stays cold.",
    "Power cord is frayed and exposed, this is a serious electrical hazard.",
    "Internal circuit fried within a week, there was a small spark from the socket.",
    "The on/off indicator light flickers and the unit randomly shuts down by itself.",
    "A part was missing from the box and now the fan assembly won't click together.",
    # Home — dehumidifier, humidifier, air purifier, drying rack
    "Dehumidifier compressor won't start, drum stays empty even after hours.",
    "Humidifier is leaking from the base and shorting itself out.",
    "Air purifier's filter housing arrived cracked, air leaks around the seal.",
    "The clothes drying rack snapped at a weld on the first load, defective frame.",
    "Smart thermostat screen is dead on arrival, no response to any touch.",
    # Weather gear
    "Umbrella's auto-open spring is broken, won't open or close properly.",
    "Rain jacket seams are coming apart along the shoulder, bad stitching.",
    "The waterproof gumboots have a hole near the sole, water leaks straight through.",
    "Dry bag's roll-top buckle snapped on the first use, not waterproof anymore.",
    "The waterproof phone pouch's seal is faulty, water got inside immediately.",
    "Rain cover for backpack has torn elastic, won't stay on at all.",
    "The travel umbrella's shaft bent on the first mild wind, clearly weak construction.",
    # Clothing — defects (seams, zippers, fabric)
    "The sweater had a huge hole near the collar when I unpacked it, defective piece.",
    "Puffer jacket's zipper is broken, teeth don't align from new.",
    "Thermal innerwear elastic snapped at the waistband on the first wear.",
    "Fleece jacket's inner lining was torn right out of the packaging.",
    "Woollen cardigan has a visible manufacturing flaw, loose threads unraveling.",
    "Cotton shirt arrived with a torn seam running down the entire side.",
    "The linen trousers' zipper is jammed and won't move either direction.",
    "Rain poncho has a tear right across the back, this item is damaged.",
    "Hooded sweatshirt's drawstring is sealed inside the hood, poor assembly.",
    "Flannel pajama buttons popped off during the first wash, defective stitching.",
    # Accessories
    "Polarised sunglasses frame snapped at the hinge after two days of normal use.",
    "The sunglass lens popped out of the frame, the glue didn't hold at all.",
    "The sun hat's brim wire is bent and poking through the fabric.",
    "Thermal gloves have holes at the fingertips, defective knit from new.",
    "Woollen beanie came with a large seam gap, feels like a factory reject.",
    "Woollen scarf is unravelling at both ends, workmanship is clearly bad.",
    "Earmuffs headband snapped the first time I adjusted them, cheap plastic.",
    "Snow boots sole is already peeling off along the toe, adhesive failure.",
    "Insulated steel bottle leaks around the cap, the seal is clearly defective.",
    "Fitness tracker screen is dead, won't power on even after a full charge.",
    "Smart watch strap buckle broke on day one, the pin fell right out.",
    "Backpack zipper is derailed and won't close, defective hardware.",
    "Hand warmers won't ignite at all, I believe the fuel cell is faulty.",
    "Cooling towel has a melted spot in the middle, looks like a manufacturing defect.",
    # Personal care (defect = packaging failure, broken bottle, leakage)
    "Sunscreen bottle arrived leaking, half the contents were spilled inside the box.",
    "The lotion pump dispenser doesn't work, broken from the start.",
    "Lip balm tube is cracked and the balm is contaminated with plastic shards.",
    "The aloe vera gel container seal was broken on arrival, product looks tampered.",
    "Sunblock stick is unusable, the twist mechanism is jammed solid.",
    # Short, blunt defect reports
    "Completely broken on arrival.",
    "Dead on arrival, won't power on at all.",
    "Burning smell within one minute of switching on.",
    "The unit is making a loud grinding noise and overheating.",
    "Smoke came out of the plug socket as soon as I turned it on.",
    "Zipper is jammed from day one, cannot use the item.",
    "Clear factory defect, has a visible crack running down the side.",
    "There is a loud rattle inside and performance drops to zero after a few minutes.",
    "The fabric is torn right out of the packaging.",
    "The item sparks when I plug it in, this is dangerous.",
    # More variations for vocabulary breadth
    "Keeps shutting down after five minutes, something is clearly wrong inside.",
    "The buttons on the control panel are completely unresponsive.",
    "This heater's safety tip-over switch doesn't work, it kept running on its side.",
    "Water tank cap won't screw on properly, it leaks every time I fill it.",
    "There's a loud buzzing coming from the motor, this is not normal operation.",
    "The threading on the water heater inlet is damaged, won't connect to the pipe.",
    "Fuse blew within the first ten minutes of use, something is drawing too much current.",
    "The LED display shows random characters, firmware or hardware is broken.",
    "The remote sensor is dead, infrared signals don't register at all.",
    "The item vibrates violently and walks across the floor, severely unbalanced.",
    "Thermal cutoff kept tripping within minutes, the heater is faulty.",
    "The compressor sounds like a cement mixer, something is grinding inside.",
    "The impeller on the dehumidifier is broken and the fan doesn't spin.",
    "Humidifier spits scalding water out of the vent, that cannot be right.",
    "The jacket's waterproof coating is already flaking off from new, not usable in rain.",
    "Boot zipper is split along the seam, the whole item is defective.",
    "The gloves' touchscreen fingertips don't register at all despite the claim.",
    "The umbrella ribs are bent and sticking out of the canopy fabric.",
    "The water heater element is burnt black, failed on the second use.",
    "There's an electrical hum and the unit's casing is live to the touch.",
    # Additional hardware defect examples covering full catalog
    "Cordless stick vacuum motor emits high-pitched whine and stopped suction entirely.",
    "The cordless stick vacuum battery refuses to charge, LED blinks red error constantly.",
    "Vacuum roller brush snapped in half on first use on a low pile rug.",
    "Tower fan oscillation gear is stripped and clicking loudly without rotating.",
    "Wall mounted fan speed regulator knob cracked off in my hand.",
    "BLDC ceiling fan remote sensor failed, fan is stuck spinning at maximum speed.",
    "Evaporative cooler float valve failed, causing continuous water overflow onto my floor.",
    "Desert air cooler louvers arrived broken off their pivot brackets.",
    "Mini rechargeable fan internal battery swelled up and popped open the plastic casing.",
    "Window AC compressor clatters furiously and blows hot air instead of cold.",
    "Halogen heater safety mesh was detached in the box, exposed heating rods.",
    "Space heater blower fan seized up, unit shut off with smoke coming out.",
    "Storage water heater thermostat failed, releasing boiling steam through the pressure valve.",
    "Electric blanket controller melted around the plug, scorched my mattress.",
    "Towel warmer rail has a severe electrical leak, tingling current felt on metal.",
    "Immersion heating rod cracked open after ten minutes in water, exposed copper element.",
    "Infrared heater stand broke at the hinge, cannot stand upright safely.",
    "Golf umbrella canopy ripped along three rib seams during light drizzle.",
    "Anti-slip rain sandals buckle snapped cleanly on first step outdoors.",
    "Rain jacket hood drawstring eyelet tore completely through the waterproof membrane.",
    "Backpack rain cover came with a massive rip across the center seam.",
    "Waterproof dry bag base seam unglued, soaked all gear inside.",
    "Cotton t-shirt hem came completely unstitched after unpacking, loose thread everywhere.",
    "Polo shirt collar was sewn crooked and one button hole was missing entirely.",
    "Sleeveless summer dress side seam split wide open upon first wear.",
    "Down jacket is leaking feathers from torn baffle stitching right out of packaging.",
    "Linen shirt has two missing buttons and a frayed buttonhole.",
    "Winter overcoat pocket lining was never sewn shut, items drop straight through.",
    "Cotton shorts zipper teeth sheared off after zipping once.",
    "Cashmere pullover has a large moth hole right in the front panel.",
    "Aviator sunglasses nose pad fell off and cannot be reattached, screw stripped.",
    "Sun visor headband plastic snapped in half while putting it on.",
    "UV arm sleeves stitching unraveled into threads on the first pull.",
    "Insulated steel bottle vacuum seal is broken, exterior gets burning hot immediately.",
    "Snow boots metal eyelet pulled right out of the leather upper.",
    "Essential oil diffuser ultrasonic plate stopped vibrating, unit won't produce any mist.",
    "Hot water bottle stopper threads are stripped, boiling water leaks out the neck.",
    "Clothes drying stand central rivet snapped, whole rack collapsed.",
    "Moisturising body lotion bottle arrived cracked down the seam, lotion leaked everywhere.",
    "Petroleum jelly tub arrived with shattered lid, glass shards mixed in product.",
]

PERSONAL_DISSATISFACTION = [
    # Appliances
    "The cooler works fine but it's way too noisy for my bedroom, not what I expected.",
    "Heater does its job but honestly I just don't like how bulky it looks in my living room.",
    "Fan is okay but I realized I don't really need it anymore, returning for a refund.",
    "I thought this cooler would cover a bigger room, it's underwhelming for the price.",
    "Heater is fine functionally, I just changed my mind and want something more compact.",
    "The fan's design clashes with my room decor, works perfectly but not for me.",
    "Cooling isn't as strong as I hoped, I expected better performance for this price point.",
    "Bought two by mistake, this one works great but I don't need a second fan.",
    "The heater is heavier than I expected and hard for me to move around, returning it.",
    "It works but I found a cheaper alternative with similar features elsewhere.",
    "The fan is quieter than advertised actually, I was hoping for more airflow though.",
    "This cooler is a bit too small for my patio, functionally it's fine.",
    "Changed my mind after seeing a better model, this heater works without issues.",
    "The fan runs great, I just don't think I'll use it enough to keep it.",
    "Heater works as described but it doesn't match the rest of my furniture.",
    "The cooler does what it says, I just expected a sleeker design for this price.",
    "Everything works fine, I simply ordered the wrong size for my room.",
    "The fan is a bit too tall for my desk, no issues with how it runs though.",
    "Heater functions properly, I just want to return it since my room already has one.",
    "The AC works but it uses more electricity than I want to deal with.",
    "The AC is fine, I just realized I need a bigger tonnage for my room size.",
    "Ceiling fan looks lovely, I just changed my mind on the colour choice.",
    "The desert cooler is too large for my balcony, works great otherwise.",
    "The oil radiator is heavier than I'd expected, doesn't fit my layout.",
    # Weather / monsoon
    "The umbrella works fine, I just prefer my old compact one more honestly.",
    "Rain jacket fits well and keeps me dry, but the colour doesn't suit me.",
    "The gumboots are perfectly functional, I just realized my size is off by a bit.",
    "Dry bag is good but I ended up getting a bigger size elsewhere, don't need this one.",
    "The travel umbrella works great, I just already had a similar one at home.",
    "The dehumidifier does its job, I just don't need it anymore after a dry spell.",
    "The humidifier works fine but it takes up more counter space than I want.",
    "The rain poncho is okay, I just prefer a proper jacket for daily rain.",
    "The waterproof phone pouch works, I just use my phone case less than I thought.",
    # Clothing — summer
    "The cotton shirt fits fine but the fabric is thinner than I expected.",
    "Linen trousers look nice, I just don't like the way they wrinkle so quickly.",
    "The sun hat fits well, I just changed my mind on the shape after wearing it once.",
    "Cotton kurta is well made, I just realized it doesn't go with my wardrobe.",
    "The sleeveless dress is lovely but a bit too casual for what I needed.",
    "The polo shirt fits but the collar sits oddly on my neck, personal preference.",
    "Shorts are great, I just already own a very similar pair.",
    "Bermuda shorts are fine, I just prefer the slim-fit version instead.",
    "The nightwear set is nice but a bit warm for the current weather, returning.",
    # Clothing — winter
    "Sweater fits well but it's a bit heavier than I'd like for layering.",
    "The puffer jacket is warm but I don't love the shade of blue in person.",
    "Thermal innerwear fits, I just realized I already have enough thermals.",
    "Fleece jacket is cozy, I just prefer a hooded style for my commute.",
    "Wool cardigan looks great, I just don't need another one at this point.",
    "The electric blanket works fine, I just prefer a thicker duvet instead.",
    "The overcoat fits well, but the length is slightly off for my height.",
    "Flannel pajamas are comfortable, I just ordered the wrong set as a gift.",
    "The hooded sweatshirt is fine, I just realized it's too casual for my needs.",
    "Woollen socks are nice, I just already have plenty of similar pairs.",
    # Accessories
    "The sunglasses look great, I just prefer a lighter frame material.",
    "Beanie fits well but the colour is slightly brighter than the photo.",
    "The scarf is lovely, I just realized the length isn't right for the way I wrap it.",
    "Earmuffs work, I just prefer wearing a beanie in cold weather instead.",
    "Snow boots fit fine, but my regular winter boots turned out to be enough.",
    "The water bottle is great, I just already own too many bottles.",
    "The fitness tracker works, I just prefer a smartwatch form factor instead.",
    "The baseball cap fits well, I just don't like how the brim sits over my eyes.",
    "The cooling towel is okay, I just didn't find myself using it often.",
    "Backpack is well-made, I just realized I prefer a different style of strap.",
    "The visor is fine, I just prefer a full-brim hat for sun protection.",
    "Thermal gloves fit well, I just picked the wrong colour by accident.",
    "The sun sleeves are okay, I just didn't like how they looked with my sports kit.",
    # Personal care
    "The sunscreen works fine, I just prefer a gel formula rather than cream.",
    "Body lotion feels nice, I just realized the fragrance is too strong for me.",
    "The lip balm works, I just already have more than enough tubes at home.",
    "Aloe vera gel is okay, I just prefer a different brand's consistency.",
    "The hand cream is fine, I just don't like the smell personally.",
    "The cold cream works well, I just already own a tub of the same thing.",
    # Short, blunt dissatisfaction
    "Just changed my mind, item works fine.",
    "Doesn't suit my style, no problem with how it works.",
    "Wrong size, otherwise completely fine.",
    "No longer needed, works as advertised.",
    "Returning for a refund, performance is fine but I don't want it anymore.",
    "Ordered by accident, no issues with the product itself.",
    "Prefer a different brand, this one functions normally.",
    "Doesn't match my room, nothing wrong with the product.",
    "Changed my mind on the colour, item is in perfect working order.",
    "Realized I don't need this at all, works without problems.",
    # More variations for vocabulary breadth
    "The size is slightly off but everything else works great.",
    "I just prefer a different design, the product itself is fine.",
    "Weather turned out milder than I expected, I don't need this.",
    "Overestimated how often I'd use it, product itself is as described.",
    "Found a better deal elsewhere, this one still works perfectly.",
    "The style doesn't suit my taste, functionally no complaints.",
    "I prefer something more portable, the product works well otherwise.",
    "Decided it's too much of an indulgence, returning something that works fine.",
    "The look is nicer in photos than in person, no quality issues though.",
    "Realized I already have one at home, no problems with this one.",
    "I expected a different texture of fabric, it's fine but not for me.",
    "The fit is slightly loose, nothing wrong with the piece itself.",
    "The fit is slightly tight, nothing wrong with the piece itself.",
    "I prefer natural fibres, no issue with how it holds up.",
    "Doesn't suit the weather here, works fine but I won't use it.",
    "Changed my mind after reading more reviews, item works as expected.",
    "Didn't realize how heavy it would be, no quality issues at all.",
    "I prefer a quieter model, this one works but is louder than I like.",
    "The design isn't my style, performance is actually good.",
    "I thought the colour was navy in the photos, works fine though.",
    "Didn't fit the space I had in mind, no complaints about the product itself.",
    "I prefer the previous generation of this product, this one works correctly.",
    "The fragrance is too strong for daily use, product itself is fine.",
    "Received as a gift but it's not my taste, works fine for whoever gets it next.",
    "I'd prefer a model with more features, no problem with how this works.",
    "I'd prefer a model with fewer features, works fine but I only want the basics.",
    "The weight distribution feels off to me, nothing broken though.",
    "I prefer a different form factor, functionally this is okay.",
    "Doesn't look as premium in person as the photos suggested, works fine.",
    "I just realized my old one is still working well, don't need this one.",
    "I'd rather have a longer warranty, performance is fine for now.",
    "Found a model with a better rating, this one does work though.",
    "Doesn't match the aesthetic of my space, no quality issues to report.",
    "I prefer a different control layout, product works correctly.",
    "The colour is slightly different from the website image, works otherwise.",
    "I realized I prefer a cordless version, this one is fine corded.",
    "I prefer a wall-mount version, this freestanding one works though.",
    "It's a bit too modern looking for my room, no complaints functionally.",
    "I'd rather have the premium model, this one does the job though.",
    "I need something more compact, this works fine but is too large for my shelf.",
    # Additional personal dissatisfaction examples covering full catalog
    "The cordless stick vacuum works well, but it's heavier than I anticipated for doing stairs.",
    "The air purifier works fine, but the white finish clashes with my walnut furniture.",
    "Smart thermostat functions perfectly, but our landlord won't permit installing it.",
    "Drying stand is sturdy and functional, but it takes up too much balcony space.",
    "Diffuser works nicely, but the LED night light is brighter than I wanted in my bedroom.",
    "The hot water bottle works fine, I just realized I already have a heating pad.",
    "Tower fan works great, but the air throw doesn't reach across my open-concept living room.",
    "The wall-mounted fan operates smoothly, I just decided to go with a ceiling fan instead.",
    "Window AC cools efficiently, but the unit blocks too much natural window light.",
    "Neck fan functions as described, but I feel self-conscious wearing it outdoors.",
    "Mini rechargeable fan works nicely, but I ended up buying a plug-in desk fan.",
    "Halogen heater warms up instantly and works well, but the bright glow disturbs my sleep.",
    "Panel heater works as advertised, but it doesn't match the minimalist look of my study.",
    "Instant water heater heats water fine, but 3 liters capacity is too small for our household.",
    "Electric heating pad works great, but I prefer using a microwaveable heat wrap.",
    "Space heater functions perfectly, but my room stays warm enough without extra heat.",
    "Golf umbrella provides great shelter, but it's too long to fit into my daily commuter backpack.",
    "Rain jacket and pants set keeps rain out well, but the neon yellow color is too loud for me.",
    "Anti-slip rain sandals are comfortable and waterproof, but the strap style doesn't match my outfit.",
    "Backpack rain cover works as intended, but my new bag already came with an integrated cover.",
    "Reusable rain poncho works well, but I decided I prefer a structured trench coat.",
    "Cotton t-shirt is good quality, but the crew neck is cut higher than I like.",
    "Polo shirt fabric and finish are fine, but the slim fit is too tight around my shoulders.",
    "Cotton summer shirt is comfortable, but the pastel yellow shade looks washed out on my skin.",
    "Sleeveless summer dress is well constructed, but the hemline hits below my knees where I dislike it.",
    "Linen shirt is great quality, but I don't want to spend time ironing it after every wash.",
    "Cotton shorts fit properly and look fine, but I received the exact same pair for my birthday.",
    "Down jacket is extremely warm and well made, but it makes me look too bulky.",
    "Winter overcoat fits well and keeps me warm, but the wool blend is itchier than I prefer against my collar.",
    "Cashmere pullover is soft and flawless, but I decided it was too expensive a purchase to justify.",
    "Fleece-lined leggings are comfortable and warm, but the charcoal color looks more like faded black.",
    "Aviator sunglasses are well made with good lenses, but the teardrop shape doesn't suit my face.",
    "Wide-brim sun hat protects well from the sun, but it blows off easily during windy walks.",
    "UV protection arm sleeves work fine, but I prefer wearing long-sleeve cotton shirts.",
    "Insulated steel bottle keeps drinks cold all day, but the 1-liter size won't fit my car's cup holder.",
    "Snow boots are warm and sturdy, but our winter trip was canceled so I don't need them.",
    "SPF 50 sunscreen applies well with good protection, but leaves a dewier finish than I like for oily skin.",
    "SPF 30 daily sunscreen works fine, but I switched to a mineral sunscreen instead.",
    "Lip balm with SPF is moisturizing, but the peppermint flavor is stronger than I like.",
    "Deep moisture cold cream works nicely, but the texture is too rich for my combination skin.",
    "Petroleum jelly is perfectly fine, but I accidentally bought a pack of two instead of one.",
]

TRAINING_DATA = [(text, "hardware_defect") for text in HARDWARE_DEFECT] + [
    (text, "personal_dissatisfaction") for text in PERSONAL_DISSATISFACTION
]
